// <auto-generated />
using System;
using System.Reflection;
using ControlParental.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ControlParental.Service.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AppPolicyDbEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "ControlParental.Domain.AppPolicyDbEntity",
                typeof(AppPolicyDbEntity),
                baseEntityType,
                propertyCount: 7,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(AppPolicyDbEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppPolicyDbEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("Relational:ColumnName", "id");

            var allowedWindowsJson = runtimeEntityType.AddProperty(
                "AllowedWindowsJson",
                typeof(string),
                propertyInfo: typeof(AppPolicyDbEntity).GetProperty("AllowedWindowsJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppPolicyDbEntity).GetField("<AllowedWindowsJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            allowedWindowsJson.AddAnnotation("Relational:ColumnName", "allowed_windows_json");

            var category = runtimeEntityType.AddProperty(
                "Category",
                typeof(string),
                propertyInfo: typeof(AppPolicyDbEntity).GetProperty("Category", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppPolicyDbEntity).GetField("<Category>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            category.AddAnnotation("Relational:ColumnName", "category");

            var dailyLimitMinutes = runtimeEntityType.AddProperty(
                "DailyLimitMinutes",
                typeof(int?),
                propertyInfo: typeof(AppPolicyDbEntity).GetProperty("DailyLimitMinutes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppPolicyDbEntity).GetField("<DailyLimitMinutes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            dailyLimitMinutes.AddAnnotation("Relational:ColumnName", "daily_limit_minutes");

            var deviceId = runtimeEntityType.AddProperty(
                "DeviceId",
                typeof(string),
                propertyInfo: typeof(AppPolicyDbEntity).GetProperty("DeviceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppPolicyDbEntity).GetField("<DeviceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            deviceId.AddAnnotation("Relational:ColumnName", "device_id");

            var packageName = runtimeEntityType.AddProperty(
                "PackageName",
                typeof(string),
                propertyInfo: typeof(AppPolicyDbEntity).GetProperty("PackageName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppPolicyDbEntity).GetField("<PackageName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            packageName.AddAnnotation("Relational:ColumnName", "package_name");

            var state = runtimeEntityType.AddProperty(
                "State",
                typeof(string),
                propertyInfo: typeof(AppPolicyDbEntity).GetProperty("State", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppPolicyDbEntity).GetField("<State>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            state.AddAnnotation("Relational:ColumnName", "state");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { deviceId, packageName },
                unique: true);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("DeviceId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("DeviceId") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var policy = declaringEntityType.AddNavigation("Policy",
                runtimeForeignKey,
                onDependent: true,
                typeof(PolicyDbEntity),
                propertyInfo: typeof(AppPolicyDbEntity).GetProperty("Policy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppPolicyDbEntity).GetField("<Policy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "app_policies");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
