// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ControlParental.Service.CompiledModels
{
    public partial class ControlParentalDbContextModel
    {
        private ControlParentalDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("ff0963ee-847c-40b6-8326-ae12ce2a6c46"), entityTypeCount: 8)
        {
        }

        partial void Initialize()
        {
            var appPolicyDbEntity = AppPolicyDbEntityEntityType.Create(this);
            var consentDbEntity = ConsentDbEntityEntityType.Create(this);
            var grantDbEntity = GrantDbEntityEntityType.Create(this);
            var outboxDbEntity = OutboxDbEntityEntityType.Create(this);
            var policyDbEntity = PolicyDbEntityEntityType.Create(this);
            var usageTodayDbEntity = UsageTodayDbEntityEntityType.Create(this);
            var foregroundEventDbEntity = ForegroundEventDbEntityEntityType.Create(this);
            var reconciliationHistoryDbEntity = ReconciliationHistoryDbEntityEntityType.Create(this);

            AppPolicyDbEntityEntityType.CreateForeignKey1(appPolicyDbEntity, policyDbEntity);
            GrantDbEntityEntityType.CreateForeignKey1(grantDbEntity, policyDbEntity);

            AppPolicyDbEntityEntityType.CreateAnnotations(appPolicyDbEntity);
            ConsentDbEntityEntityType.CreateAnnotations(consentDbEntity);
            GrantDbEntityEntityType.CreateAnnotations(grantDbEntity);
            OutboxDbEntityEntityType.CreateAnnotations(outboxDbEntity);
            PolicyDbEntityEntityType.CreateAnnotations(policyDbEntity);
            UsageTodayDbEntityEntityType.CreateAnnotations(usageTodayDbEntity);
            ForegroundEventDbEntityEntityType.CreateAnnotations(foregroundEventDbEntity);
            ReconciliationHistoryDbEntityEntityType.CreateAnnotations(reconciliationHistoryDbEntity);

            AddAnnotation("ProductVersion", "9.0.0");
        }
    }
}
