// <auto-generated />
using System;
using System.Reflection;
using ControlParental.Domain;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ControlParental.Service.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class OutboxDbEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "ControlParental.Domain.OutboxDbEntity",
                typeof(OutboxDbEntity),
                baseEntityType,
                propertyCount: 16,
                unnamedIndexCount: 4,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(OutboxDbEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxDbEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("Relational:ColumnName", "id");

            var attempts = runtimeEntityType.AddProperty(
                "Attempts",
                typeof(int),
                propertyInfo: typeof(OutboxDbEntity).GetProperty("Attempts", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxDbEntity).GetField("<Attempts>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            attempts.AddAnnotation("Relational:ColumnName", "attempts");

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(OutboxDbEntity).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxDbEntity).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdAt.AddAnnotation("Relational:ColumnName", "created_at");

            var dedupKey = runtimeEntityType.AddProperty(
                "DedupKey",
                typeof(string),
                propertyInfo: typeof(OutboxDbEntity).GetProperty("DedupKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxDbEntity).GetField("<DedupKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            dedupKey.AddAnnotation("Relational:ColumnName", "dedup_key");

            var eventType = runtimeEntityType.AddProperty(
                "EventType",
                typeof(string),
                propertyInfo: typeof(OutboxDbEntity).GetProperty("EventType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxDbEntity).GetField("<EventType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            eventType.AddAnnotation("Relational:ColumnName", "event_type");

            var lastAttemptAt = runtimeEntityType.AddProperty(
                "LastAttemptAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(OutboxDbEntity).GetProperty("LastAttemptAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxDbEntity).GetField("<LastAttemptAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastAttemptAt.AddAnnotation("Relational:ColumnName", "last_attempt_at");

            var lastError = runtimeEntityType.AddProperty(
                "LastError",
                typeof(string),
                propertyInfo: typeof(OutboxDbEntity).GetProperty("LastError", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxDbEntity).GetField("<LastError>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastError.AddAnnotation("Relational:ColumnName", "last_error");

            var payloadJson = runtimeEntityType.AddProperty(
                "PayloadJson",
                typeof(string),
                propertyInfo: typeof(OutboxDbEntity).GetProperty("PayloadJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxDbEntity).GetField("<PayloadJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            payloadJson.AddAnnotation("Relational:ColumnName", "payload_json");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(OutboxEntryStatus),
                propertyInfo: typeof(OutboxDbEntity).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OutboxDbEntity).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: OutboxEntryStatus.Pending);
            status.AddAnnotation("Relational:ColumnName", "status");
            status.AddAnnotation("Relational:DefaultValue", 0);
            status.AddAnnotation("Relational:DefaultValueSql", "0");

            var operationId = runtimeEntityType.AddProperty("OperationId", typeof(string), propertyInfo: typeof(OutboxDbEntity).GetProperty("OperationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly), fieldInfo: typeof(OutboxDbEntity).GetField("<OperationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            operationId.AddAnnotation("Relational:ColumnName", "operation_id");
            operationId.AddAnnotation("Relational:DefaultValue", string.Empty);
            var claimVersion = runtimeEntityType.AddProperty("ClaimVersion", typeof(long), propertyInfo: typeof(OutboxDbEntity).GetProperty("ClaimVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly), fieldInfo: typeof(OutboxDbEntity).GetField("<ClaimVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly), sentinel: 0L);
            claimVersion.AddAnnotation("Relational:ColumnName", "claim_version");
            claimVersion.AddAnnotation("Relational:DefaultValue", 0L);
            claimVersion.AddAnnotation("Relational:DefaultValueSql", "0");
            var claimedUntil = runtimeEntityType.AddProperty("ClaimedUntil", typeof(DateTimeOffset?), propertyInfo: typeof(OutboxDbEntity).GetProperty("ClaimedUntil", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly), fieldInfo: typeof(OutboxDbEntity).GetField("<ClaimedUntil>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly), nullable: true);
            claimedUntil.AddAnnotation("Relational:ColumnName", "claimed_until");
            var nextEligibleAt = runtimeEntityType.AddProperty("NextEligibleAt", typeof(DateTimeOffset?), propertyInfo: typeof(OutboxDbEntity).GetProperty("NextEligibleAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly), fieldInfo: typeof(OutboxDbEntity).GetField("<NextEligibleAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly), nullable: true);
            nextEligibleAt.AddAnnotation("Relational:ColumnName", "next_eligible_at");
            var deadLetteredAt = runtimeEntityType.AddProperty("DeadLetteredAt", typeof(DateTimeOffset?), propertyInfo: typeof(OutboxDbEntity).GetProperty("DeadLetteredAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly), fieldInfo: typeof(OutboxDbEntity).GetField("<DeadLetteredAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly), nullable: true);
            deadLetteredAt.AddAnnotation("Relational:ColumnName", "dead_lettered_at");
            var safeFailureCode = runtimeEntityType.AddProperty("SafeFailureCode", typeof(string), propertyInfo: typeof(OutboxDbEntity).GetProperty("SafeFailureCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly), fieldInfo: typeof(OutboxDbEntity).GetField("<SafeFailureCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly), nullable: true);
            safeFailureCode.AddAnnotation("Relational:ColumnName", "safe_failure_code");
            var auditReference = runtimeEntityType.AddProperty("AuditReference", typeof(string), propertyInfo: typeof(OutboxDbEntity).GetProperty("AuditReference", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly), fieldInfo: typeof(OutboxDbEntity).GetField("<AuditReference>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly), nullable: true);
            auditReference.AddAnnotation("Relational:ColumnName", "audit_reference");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { createdAt });

            var index0 = runtimeEntityType.AddIndex(
                new[] { dedupKey },
                unique: true);

            runtimeEntityType.AddIndex(new[] { status, nextEligibleAt, createdAt });
            runtimeEntityType.AddIndex(new[] { operationId });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "outbox");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
