// <auto-generated />
using System;
using System.Reflection;
using ControlParental.Domain;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ControlParental.Service.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class UsageTodayDbEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "ControlParental.Domain.UsageTodayDbEntity",
                typeof(UsageTodayDbEntity),
                baseEntityType,
                propertyCount: 5,
                keyCount: 1);

            var appId = runtimeEntityType.AddProperty(
                "AppId",
                typeof(string),
                propertyInfo: typeof(UsageTodayDbEntity).GetProperty("AppId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UsageTodayDbEntity).GetField("<AppId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            appId.AddAnnotation("Relational:ColumnName", "app_id");

            var serverDate = runtimeEntityType.AddProperty(
                "ServerDate",
                typeof(DateOnly),
                propertyInfo: typeof(UsageTodayDbEntity).GetProperty("ServerDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UsageTodayDbEntity).GetField("<ServerDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new DateOnly(1, 1, 1));
            serverDate.AddAnnotation("Relational:ColumnName", "server_date");

            var elapsedSeconds = runtimeEntityType.AddProperty(
                "ElapsedSeconds",
                typeof(long),
                propertyInfo: typeof(UsageTodayDbEntity).GetProperty("ElapsedSeconds", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UsageTodayDbEntity).GetField("<ElapsedSeconds>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            elapsedSeconds.AddAnnotation("Relational:ColumnName", "elapsed_seconds");

            var lastUpdated = runtimeEntityType.AddProperty(
                "LastUpdated",
                typeof(DateTimeOffset),
                propertyInfo: typeof(UsageTodayDbEntity).GetProperty("LastUpdated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UsageTodayDbEntity).GetField("<LastUpdated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            lastUpdated.AddAnnotation("Relational:ColumnName", "last_updated");

            var minutes = runtimeEntityType.AddProperty(
                "Minutes",
                typeof(int),
                propertyInfo: typeof(UsageTodayDbEntity).GetProperty("Minutes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UsageTodayDbEntity).GetField("<Minutes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            minutes.AddAnnotation("Relational:ColumnName", "minutes");

            var key = runtimeEntityType.AddKey(
                new[] { appId, serverDate });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "usage_today");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
